### ISSUE TITLE
70-yubikey.rules Checks for ConsoleKit

### ISSUE THREAD

**Issue by rmackinnon** [ldrumm/yubikey-totp-gui#5]
Using the applied UDEV rule on a now current SystemD supported OS fails to run.  Generally it's not very clear why it is checking for the ConsoleKit database.  Some users did not run ConsoleKit (as it was a single user machine), and is now out of date with most systems using SystemD.

**Comment by ldrumm** [comment]
@rmackinnon I've made some changes to `setup.py` that I think might fix this issue at installation time. Is there any chance you can check the new udev rules make sense?

**Comment by rmackinnon** [comment]
@ldrumm Sure lemme give'em a quick look.

**Comment by rmackinnon** [comment]
@ldrumm,

So I've done some thinking about this.  There are a couple of errors (reads: typos) in the udev rules as submitted in `setup.py`, and honestly I think you could skip outputting the rule files all together as your `README.rst` totally mitigates the need for your `setup.py` to create any such rules.  Since you instruct the linux users to curl the rules from the head maintained by @Yubico, there is no logical reason for you yourself or any other maintainer for the project to maintain these udev rules.  By simply having `setup.py` check for the existence of the files and throw up some warning text about "blah blah rule not existing, and they should curl blah blah blah...", you'd end up giving a better experience to the user and increase ease of maintainability. ;D

The secondary reason I'm stating all of this, after taking a second hard look at my own udev rules, testing what I had with attempting to check the configs with `yubikey-personalization-gui`, and comparing them with @Yubico 's: I've come to the conclusion that my rule bugs really should be submitting upstream to them.  Completely unrelated to this, the rules they post don't really work, and are just like yours, so makes sense that I submit an issue to them.

FYI, the udev rules that I use for my NEO are:

```
ACTION!="add|change", GOTO="yubico_end"

SUBSYSTEM=="usb", \
  ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0010|0110|0111|0113|0114|0115|0116|0120|0401|0402|0403|0405|0407|0410", \
  ENV{ID_SECURITY_TOKEN}="1", \
  GROUP="plugdev", \
  MODE="0664", \
  TAG+="uaccess",\
  TAG+="udev-acl" 

LABEL="yubico_end"
```

And for U2F support:

```
ACTION!="add|change", GOTO="u2f_end"

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", \
    ATTRS{idVendor}=="2581", ATTRS{idProduct}=="f1d0", \
    GROUP="plugdev", \
    MODE="0660", \
    ENV{ID_U2F_TOKEN}="1", \
    TAG+="uaccess"

LABEL="u2f_end"
```

Cheers,
--Rob

**Comment by rmackinnon** [comment]
Closing low hanging fruit, that I opened, and don't need to be alive anymore.
